### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yukina3230** [khaled-0/gnome-cloudflare-warp-toggle#1]
Hi @khaled-0 , GNOME 45 beta has been released, do you have any plans to port it to the new version? (May need some changes)

This link might help: [https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm)

Thank you.

**Comment by khaled-0** [comment]
Thanks for notifying, I'll look into it as soon as I can. Maybe within a few days

**Comment by khaled-0** [comment]
Done and Approved. Can you test it so I can close this issue.

**Comment by yukina3230** [comment]
Thanks, I'm currently using GNOME 44 on Arch, I'll test it and let you know when the next version is in the stable repo.
